### ISSUE TITLE
release to debs

### ISSUE THREAD

**Issue by mintar** [uos/rviz_fps_plugin#3]
Since this repo is of interest to people outside UOS, let's release it to .deb packages. I can do it, no problem (but first we should set up per-distro branches, see #2).

@hdeeken @jspricke What do you think?

**Comment by hdeeken** [comment]
sounds good! i never created a .deb, maybe we can do that together?!

however there are some small features I would like to implement first (a config gui etc.).
i'll come back to you soon ;)

**Comment by mintar** [comment]
Yes, let's do that together. I'll be back in Osnabrück on Jan 22. Just trigger me then. :)

**Comment by hdeeken** [comment]
Great!
