### ISSUE TITLE
Rviz Seg Faults when used with ROS Kinetic

### ISSUE THREAD

**Issue by bharadwajakshay** [uos/rviz_fps_plugin#6]
Hey,

I tried to use this plugin with ROS kinetic, but Rviz seg faults when either the plugin is loaded or the view controller is changed to FPSMotion. Have you seen similar behavior?  

Thanks

**Comment by mintar** [comment]
Hi @spacemanspiff0211! I haven't used this repo in a long time (probably never on kinetic), and the last code update was 3 years ago. So you should consider this repo unmaintained. If you want to use the code here, you'll have to fix it yourself, sorry. :(

If you do make it compatible with kinetic, and you want to contribute a pull request, I'd be happy to review it though!

**Comment by albee** [comment]
Hi @mintar I've fixed this in a pull request. I'm able to compile and run the RViz plugin on ROS Kinetic (updated CMakeLists.txt to QT5). I ran across this plugin after looking for a better way to navigate RViz, I hope others can continue using it in future ROS distros!

**Comment by jspricke** [comment]
Should be fixed with #9.
